Для начала спарсим все стихи Маяковского с одной страницы

In [5]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import requests
from bs4 import BeautifulSoup
import re

# Открываем нужную страницу
options = Options()
options.add_argument('--headless')
options.add_argument('--disable-gpu')
options.add_argument('--window-size=1920,1080')

# Запускаем браузер
driver = webdriver.Chrome(options=options)

# Открываем страницу
driver.get("https://rustih.ru/vse-stixi-mayakovskogo-na-odnoj-stranice/")

# Ждём немного, чтобы всё загрузилось
try:
    block = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CLASS_NAME, 'display-posts-listing'))
    )

    # Ищем все <a> внутри этого блока
    link_elements = block.find_elements(By.TAG_NAME, 'a')
    urls = [link.get_attribute('href') for link in link_elements if link.get_attribute('href')]

    print(f"Найдено ссылок: {len(urls)}")
    for url in urls:
        print(url)

except Exception as e:
    print("Блок или ссылки не найдены:", e)


# Проходим по каждой ссылке по очереди


driver.quit()

Найдено ссылок: 1320
https://rustih.ru/vladimir-mayakovskij-1-maya/
https://rustih.ru/vladimir-mayakovskij-1-maya-poety-narod-doshlyj/
https://rustih.ru/vladimir-mayakovskij-1-maya-sveti-vovsyu-nebes-solnceglaze/
https://rustih.ru/vladimir-mayakovskij-100-sto-procentov/
https://rustih.ru/vladimir-mayakovskij-150-000-000-sto-pyatdesyat-millionov/
https://rustih.ru/vladimir-mayakovskij-17-aprelya/
https://rustih.ru/vladimir-mayakovskij-19-dekabrya-pribylo-v-xarkov-i-napravleno-v-donbass-rosta-916/
https://rustih.ru/vladimir-mayakovskij-3-goda-tomu-nazad-burzhuaziya-krichala-pro-krasnuyu-armiyu-rosta-522/
https://rustih.ru/vladimir-mayakovskij-6-monaxin/
https://rustih.ru/vladimir-mayakovskij-7-chasov/
https://rustih.ru/vladimir-mayakovskij-9-e-yanvarya/
https://rustih.ru/vladimir-mayakovskij-iii-internacional/
https://rustih.ru/vladimir-mayakovskij-iv-internacional/
https://rustih.ru/vladimir-mayakovskij-notre-dame/
https://rustih.ru/vladimir-mayakovskij-xiv-myud/
https://rustih.ru/vladi

In [9]:
all_majak_texts=[]
for url in urls:
    response = requests.get(url)
    print(f'Ссылка открыта :{url}')
    html = response.text  # или response.content

# 2. Разбираем HTML через BeautifulSoup
    soup = BeautifulSoup(html, 'html.parser')
    div=soup.find('div',class_='entry-content poem-text')
    text=div.get_text()
    text=text.replace('\n',' ')
    all_majak_texts.append(text)
    time.sleep(1)

Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-1-maya/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-1-maya-poety-narod-doshlyj/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-1-maya-sveti-vovsyu-nebes-solnceglaze/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-100-sto-procentov/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-150-000-000-sto-pyatdesyat-millionov/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-17-aprelya/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-19-dekabrya-pribylo-v-xarkov-i-napravleno-v-donbass-rosta-916/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-3-goda-tomu-nazad-burzhuaziya-krichala-pro-krasnuyu-armiyu-rosta-522/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-6-monaxin/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-7-chasov/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-9-e-yanvarya/
Ссылка открыта :https://rustih.ru/vladimir-mayakovskij-iii-internacional/
Ссылка от

In [2]:
with open(r'C:\Users\yaneg\.git\py\NLP\mayakovsky_poems.txt', 'w', encoding='utf-8') as f:
    for poem in all_majak_texts:
        f.write(poem)
        f.write('\n\n')

NameError: name 'all_majak_texts' is not defined

In [ ]:

url = 'https://rustih.ru/vladimir-mayakovskij-1-maya/'  # замените на нужную ссылку

text

In [1]:
with open(r'C:\Users\yaneg\.git\py\NLP\mayakovsky_poems.txt', 'r', encoding='utf-8') as file:
    text = file.read()
    
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1709500


Посчитаем количество каждого уникального элемента, чтобы понимать, что надо почистить

In [2]:

char_freq = {}

for char in text:
    if char in char_freq:
        char_freq[char] += 1
    else:
        char_freq[char] = 1
        
# for char, count in sorted(char_freq.items(), key=lambda x: -x[1]):
#     print(f"{repr(char)}: {count}")
sorted_items = sorted(char_freq .items(), key=lambda x: x[1], reverse=False)
sorted_items

[('Z', 1),
 ('ö', 1),
 ('U', 1),
 ('j', 1),
 ('à', 1),
 ('“', 1),
 ('”', 1),
 ('é', 1),
 ('z', 1),
 ('x', 1),
 ('Ё', 1),
 ('×', 1),
 ('}', 1),
 ('f', 1),
 ('W', 1),
 ('K', 2),
 ('J', 2),
 ('w', 2),
 ('H', 2),
 ('L', 2),
 ('y', 2),
 ('ü', 2),
 ('D', 3),
 ('M', 3),
 ('=', 3),
 ('N', 4),
 ('G', 4),
 ('O', 4),
 ('‘', 4),
 ('T', 4),
 ('B', 5),
 ('p', 5),
 ('P', 5),
 ('/', 5),
 ('b', 5),
 ('ѣ', 5),
 ('\u200e', 5),
 ('g', 6),
 ('v', 6),
 ('R', 6),
 ('E', 6),
 ('C', 7),
 ('A', 7),
 ('h', 8),
 ('½', 8),
 ('S', 9),
 ('[', 9),
 (']', 9),
 ('’', 14),
 ('c', 15),
 ('№', 15),
 ('V', 17),
 ('m', 18),
 ('Ы', 19),
 ('t', 20),
 ('u', 20),
 ('s', 22),
 ('d', 23),
 ('l', 23),
 ('<', 23),
 ('X', 23),
 ('>', 24),
 ('i', 25),
 ('%', 26),
 ('n', 28),
 ('·', 30),
 ('Ь', 32),
 ('o', 33),
 ('Щ', 36),
 ('r', 38),
 ('a', 46),
 ('_', 54),
 ('Й', 59),
 ('\u2004', 63),
 ('e', 67),
 ('\xa0', 73),
 ('Ю', 80),
 ('I', 124),
 ('Ц', 133),
 ('̀', 162),
 ('\u2003', 162),
 (';', 198),
 ('*', 247),
 ('\t', 256),
 ('–', 277),
 

Уберем редко-встречающиеся символы

In [3]:
import re

# text = re.sub(r'[A-Za-z]', '', text)
def normalize_text(text):
    replacements = {
    # Кавычки и тире
    '“': '"', '”': '"',
    '‘': "'", '’': "'",
    '—': '-', '–': '-',
    '…': '...',
    '«': '"', '»': '"',

    # Невидимые пробелы и неразрывные
    '\u2003': ' ',
    '\u2004': ' ',
    '\u200e': ' ',
    '\xa0': ' ',
    '\u202f': ' ',
    '\u00ad': '',  # soft hyphen

    # Экзотика
    '×': '',
    '½': '',
    '̀': '',
    '́': '',
    '·': '',
    '№': '',
    'à': '', 'é': '', 'ö': '', 'ü': '',
    'ѣ': '',
    'Ё': '',

    # Технические символы
    '=': '', '/': '', '[': '', ']': '', '{': '', '}': '',
    '<': '', '>': '', '_': '', '%': '', ';': '', '*': '',

    # Английские буквы (удаление)
    **{ch: '' for ch in 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'}
}
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text
text=normalize_text(text)

In [4]:
char_freq = {}

for char in text:
    if char in char_freq:
        char_freq[char] += 1
    else:
        char_freq[char] = 1
        
# for char, count in sorted(char_freq.items(), key=lambda x: -x[1]):
#     print(f"{repr(char)}: {count}")
sorted_items = sorted(char_freq .items(), key=lambda x: x[1], reverse=False)
sorted_items

[("'", 18),
 ('Ы', 19),
 ('Ь', 32),
 ('Щ', 36),
 ('Й', 59),
 ('Ю', 80),
 ('Ц', 133),
 ('\t', 256),
 ('Ж', 280),
 ('ъ', 323),
 ('Ш', 336),
 ('8', 377),
 ('7', 422),
 ('Ф', 448),
 ('9', 450),
 ('6', 517),
 ('Х', 562),
 ('5', 636),
 ('ё', 764),
 ('Я', 770),
 ('Э', 852),
 ('4', 857),
 ('(', 880),
 ('У', 887),
 ('Е', 913),
 ('3', 914),
 (')', 940),
 ('0', 1071),
 ('Л', 1102),
 ('З', 1140),
 ('2', 1277),
 ('Г', 1302),
 ('Ч', 1478),
 ('Б', 1549),
 ('Р', 1847),
 ('Д', 1979),
 ('О', 1979),
 ('1', 2004),
 ('Т', 2047),
 ('А', 2228),
 ('И', 2354),
 ('?', 2561),
 ('М', 2625),
 ('\n', 2640),
 ('ф', 2651),
 (':', 2779),
 ('К', 3071),
 ('э', 3235),
 ('С', 3751),
 ('Н', 3912),
 ('П', 4319),
 ('В', 4515),
 ('щ', 5329),
 ('"', 5392),
 ('ц', 6339),
 ('!', 7237),
 ('ю', 9073),
 ('ш', 12107),
 ('х', 12403),
 ('-', 12409),
 ('ж', 12888),
 ('ч', 17590),
 ('й', 19609),
 ('г', 21442),
 ('б', 23279),
 ('з', 23424),
 ('ы', 25653),
 ('ь', 26068),
 ('я', 26213),
 (',', 27714),
 ('.', 31410),
 ('п', 32168),
 ('у', 3

In [5]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"'(),-.0123456789:?АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяё
87


In [6]:
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string


In [9]:
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([1709119]) torch.int64
tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59, 64, 72, 62, 56,  3,  2, 46, 59,
        65, 68, 56, 59, 77, 59, 71, 72, 56, 68,  3,  2, 35, 54, 71, 71, 54,  3,
         2, 27, 68, 56, 68, 65, 82, 67, 68,  2, 66, 54, 85, 72, 82, 71, 85, 10,
         2, 35, 54, 59, 66,  2, 70, 54, 61, 66, 54, 63, 71, 85,  3,  2, 25,  2,
        73, 65, 62, 76, 81,  3,  2, 33,  2, 67, 68, 57, 59,  2, 67, 68, 57, 54,
         3,  2, 25, 71, 85, 64, 62, 63,  2, 65, 59, 58,  2, 69, 68, 58,  2, 67,
        54, 66, 62,  2, 65, 68, 66, 54, 63, 71, 85,  3,  2, 41, 54, 63, 72, 59,
         2, 56, 71, 59,  2, 71, 67, 59, 57, 54,  3,  2, 12,  2, 66, 54, 85,  2,
        69, 73, 71, 72, 82,  2, 64, 54, 60, 58, 81, 63,  2, 78, 54, 57,  8,  2,
        56,  2, 55, 73, 65, 81, 60, 67, 62, 64,  2, 73, 58, 54, 70, 59, 67, 67,
        81, 63,  8,  2, 64, 54, 60, 58, 68, 59,  2, 70, 54, 58, 62, 68,  8,  2,
        38, 54, 70, 62, 60, 54, 66,  2, 68, 72, 58, 54, 67, 67, 68, 59,  8,  2,
      

In [10]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [11]:
block_size = 32
train_data[:block_size+1]

tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59, 64, 72, 62, 56,  3,  2, 46, 59,
        65, 68, 56, 59, 77, 59, 71, 72, 56, 68,  3,  2, 35, 54, 71])

In [12]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([2]) the target: 35
when input is tensor([ 2, 35]) the target: 81
when input is tensor([ 2, 35, 81]) the target: 3
when input is tensor([ 2, 35, 81,  3]) the target: 2
when input is tensor([ 2, 35, 81,  3,  2]) the target: 33
when input is tensor([ 2, 35, 81,  3,  2, 33]) the target: 68
when input is tensor([ 2, 35, 81,  3,  2, 33, 68]) the target: 65
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65]) the target: 65
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65]) the target: 59
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59]) the target: 64
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59, 64]) the target: 72
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59, 64, 72]) the target: 62
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59, 64, 72, 62]) the target: 56
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65, 65, 59, 64, 72, 62, 56]) the target: 3
when input is tensor([ 2, 35, 81,  3,  2, 33, 68, 65

In [13]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 2, 71, 62, 85, 84, 72,  2, 56],
        [64, 73, 61, 67, 62, 77, 67, 68],
        [68, 67, 62, 56, 78, 62, 71, 82],
        [58, 62, 67,  2, 69, 59, 70, 56]])
targets:
torch.Size([4, 8])
tensor([[71, 62, 85, 84, 72,  2, 56, 59],
        [73, 61, 67, 62, 77, 67, 68, 63],
        [67, 62, 56, 78, 62, 71, 82,  2],
        [62, 67,  2, 69, 59, 70, 56, 54]])
----
when input is [2] the target: 71
when input is [2, 71] the target: 62
when input is [2, 71, 62] the target: 85
when input is [2, 71, 62, 85] the target: 84
when input is [2, 71, 62, 85, 84] the target: 72
when input is [2, 71, 62, 85, 84, 72] the target: 2
when input is [2, 71, 62, 85, 84, 72, 2] the target: 56
when input is [2, 71, 62, 85, 84, 72, 2, 56] the target: 59
when input is [64] the target: 73
when input is [64, 73] the target: 61
when input is [64, 73, 61] the target: 67
when input is [64, 73, 61, 67] the target: 62
when input is [64, 73, 61, 67, 62] the target: 77
when input is [64, 

In [14]:
print(xb)

tensor([[ 2, 71, 62, 85, 84, 72,  2, 56],
        [64, 73, 61, 67, 62, 77, 67, 68],
        [68, 67, 62, 56, 78, 62, 71, 82],
        [58, 62, 67,  2, 69, 59, 70, 56]])


In [15]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 87])
tensor(4.7299, grad_fn=<NllLossBackward0>)
	4,Д6ЭШыт05)ЦЕсгй3ЩцутНЬрмЯ8'1ЩЯш!д
сУг8ЬжаЖ1ЭнИРЧ5ГГл6ч.к0
КЮХр2аЙН.,ДЬЖГКЖлО.,4пРъ	д7АУлОцЫЛоьЦЦТ4и


In [17]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# параметры
max_steps = 100000
eval_interval = 500  # как часто делать валидацию
patience = 5         # через сколько "провалов" остановиться
best_val_loss = float('inf')
patience_counter = 0
# batch_size = 128
# block_size=128

train_losses = []
val_losses = []

for step in range(max_steps):
    # 1. получаем батч
    xb, yb = get_batch('train')

    # 2. обучение
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    if step % 1000 == 0:
        print(f"Step {step}, Loss: {loss.item():.4f}")
    # 3. замеряем валидацию
    if step % eval_interval == 0:
        m.eval()
        with torch.no_grad():
            val_loss_list = []
            for _ in range(10):  # можно увеличить для стабильности
                xb_val, yb_val = get_batch('val')
                _, val_loss = m(xb_val, yb_val)
                val_loss_list.append(val_loss.item())
            avg_val_loss = sum(val_loss_list) / len(val_loss_list)

        print(f"Step {step}: val_loss = {avg_val_loss:.4f}")

        val_losses.append(avg_val_loss)
        m.train()

        # 4. early stopping
        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            patience_counter = 0
            torch.save(m.state_dict(), 'best_model.pt')
            m.load_state_dict(torch.load('best_model.pt'))
        else:
            patience_counter += 1
            print(f"No improvement. Patience left: {patience - patience_counter}")

        if patience_counter >= patience:
            print(f"⏹️ Early stopping triggered at step {step}")
            break

Step 0, Loss: 4.7810
Step 0: val_loss = 5.1189
Step 500: val_loss = 4.7378
Step 1000, Loss: 4.4241
Step 1000: val_loss = 4.4302
Step 1500: val_loss = 4.1717
Step 2000, Loss: 3.8719
Step 2000: val_loss = 4.0748
Step 2500: val_loss = 3.8902
Step 3000, Loss: 3.4661
Step 3000: val_loss = 3.6737
Step 3500: val_loss = 3.4528
Step 4000, Loss: 3.2322
Step 4000: val_loss = 3.5094
No improvement. Patience left: 4
Step 4500: val_loss = 3.4095
Step 5000, Loss: 3.0091
Step 5000: val_loss = 3.1072
Step 5500: val_loss = 3.1991
No improvement. Patience left: 4
Step 6000, Loss: 3.0261
Step 6000: val_loss = 3.1333
No improvement. Patience left: 3
Step 6500: val_loss = 3.1387
No improvement. Patience left: 2
Step 7000, Loss: 2.9161
Step 7000: val_loss = 2.9617
Step 7500: val_loss = 3.0464
No improvement. Patience left: 4
Step 8000, Loss: 2.8370
Step 8000: val_loss = 3.0110
No improvement. Patience left: 3
Step 8500: val_loss = 3.0103
No improvement. Patience left: 2
Step 9000, Loss: 2.8825
Step 9000: val

In [19]:
# batch_size = 64
# block_size=64
for steps in range(50000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    if steps % 1000 == 0:
        print(f"Step {steps}, Loss: {loss.item():.4f}")

print(loss.item())


Step 0, Loss: 2.9129
Step 1000, Loss: 2.7309


KeyboardInterrupt: 

In [127]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	мазма, Нея" ружушемаришух етаматорай и т мо У устьско лю коковитето у г чтонеедепоете зводебеламе, пу. ст орвста к Мумня. клюслоле в ва. За Науле Вестколароияй Ною д, вовросячри прдав осятелющичть  у Врукой н. вон к Малелы. сткам кияюце нососенокийдьны эте олум прив нфазазакусеноеднысл в нутемимо к -м млуск" утате Гдлигдат ф". всв вта вшанымипо что. у), оале, длови нией снеть этаешьшьшеть ри игу м ро?! о Си битоле Несе имострит ва. устьшица поне пемпрюбогрло Чтьсе. - Гдрунадыза РРил ийскими почк


In [20]:
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [21]:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [22]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [23]:
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2, atol=1e-6)

True

In [24]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3, atol=1e-6)

True

In [25]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [26]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [27]:
k.var()

tensor(1.0449)

In [28]:
q.var()

tensor(1.0700)

In [29]:
wei.var()

tensor(1.0918)

In [30]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [31]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [145]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [146]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [147]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [153]:
import torch
print(torch.__version__)

2.6.0+cpu


In [159]:
import torch

print("CUDA доступен:", torch.cuda.is_available())

CUDA доступен: False


In [1]:
import torch

print("Версия PyTorch:", torch.__version__)
print("CUDA доступен:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Версия PyTorch: 2.6.0+cu118
CUDA доступен: True
GPU: NVIDIA GeForce GTX 1050 Ti


In [36]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 128 # how many independent sequences will we process in parallel?
block_size = 128 # what is the maximum context length for predictions?
max_iters = 20000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
if device == 'cuda':
    print(f"✅ Используется GPU: {torch.cuda.get_device_name(0)}")
else:
    print("⚠️ Используется CPU (GPU не найден)")
eval_iters = 200
n_embd = 128
n_head = 8
n_layer = 8
dropout = 0.1
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt


# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

✅ Используется GPU: NVIDIA GeForce GTX 1050 Ti
1.622103 M parameters
step 0: train loss 4.6577, val loss 4.6743
step 100: train loss 2.7117, val loss 2.7679
step 200: train loss 2.6167, val loss 2.4791
step 300: train loss 2.5176, val loss 2.3778
step 400: train loss 2.4059, val loss 2.2508
step 500: train loss 2.3026, val loss 2.1599
step 600: train loss 2.2156, val loss 2.0877
step 700: train loss 2.1416, val loss 2.0175
step 800: train loss 2.0790, val loss 1.9609
step 900: train loss 2.0249, val loss 1.9200
step 1000: train loss 1.9794, val loss 1.8748
step 1100: train loss 1.9423, val loss 1.8540
step 1200: train loss 1.9080, val loss 1.8213
step 1300: train loss 1.8773, val loss 1.8047
step 1400: train loss 1.8505, val loss 1.7780
step 1500: train loss 1.8309, val loss 1.7689
step 1600: train loss 1.8114, val loss 1.7512
step 1700: train loss 1.7928, val loss 1.7422
step 1800: train loss 1.7758, val loss 1.7249
step 1900: train loss 1.7591, val loss 1.7192
step 2000: train loss 1